### ISSUE TITLE
signup front end integration

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/contracts#45]
- [x] add signup button in nav bar
- [x] create signup page
- [x] create profile page

**Comment by virgile-dev** [comment]
Signup page: 
<img width="747" alt="capture d ecran 2018-04-22 a 12 14 24" src="https://user-images.githubusercontent.com/11473995/39093875-d6f9b53c-4626-11e8-906f-396c347bd114.png">

Profile page with transaction status:
<img width="812" alt="capture d ecran 2018-04-22 a 12 23 41" src="https://user-images.githubusercontent.com/11473995/39093946-139a66fc-4628-11e8-823e-d57c45741579.png">

**Comment by aecc** [comment]
@LucasIsasmendi why is this closed? This is still missing:

1. "You are in view mode": Sign up button. Mine says "profile" for some reason.
2. "Please install Metamask" is missing
3. It shows full screen, is that intended?

**Comment by LucasIsasmendi** [comment]
@aecc 
1. Was closed because we can not apply the same concept of **sign up** in a blockchain dapp, the smart contract is open to everyone. Also we are relying on email, something that we can't validate: how validate the ownership of the email that was stored into IPFS through the smart contract?. A solution is to use a generic field of 30 chars to store any user information
That was the main reason to switch to profile.
We need to discuss this in a new issue.
2. Yes, adding that one.
3. The idea is work with css, no angular material design, @AlexJupiter  will be doing that UI part

**Comment by aecc** [comment]
1. I understand there is no validation to do, however the voters **do need** to sign up to the contract to be able to interact with it by calling the blockchain registerNewVoter() function. Besides, the **sign up** button gives a familiar and "skeuomorph" sense to what the user must do before being able to interact. I believe @AlexJupiter might agree on that.

If you think that we should split this task in multiple others ("Please install Metamask", user validation, fullscreen, etc) feel free to do it. However I'm a fan of having everything written down on github issues so we can really understand what is missing and what we need to work on. So if we close this issue let's create others that reflect what we will do.

**Comment by LucasIsasmendi** [comment]
In the smart contract you can `createNewBallot()` without `registerNewVoter()`, so there is no user validation in the backend. Will we change this in the future?
Also email verification is a process of 3 steps: you get the user email, send a token validation to the email account and then you validate the user when clicks in the token. We don't have that in blockchain space since key pair is the user identity

**Comment by aecc** [comment]
Yes, there needs to be validation for creating a new Ballot, it's actaully commented out with a TODO. We commented it for hackaton purposes.
If we cannot do this type of validation, I propose to skip the validation topic for a discussion in another issue and leave the signup form to add a name and register yourself as a voter

**Comment by LucasIsasmendi** [comment]
Perfect, I will add that validation again and use only to register yourself
